// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odbqjxqfjijpcwdfhpcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kYnFqeHFmamlqcGN3ZGZocGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjU5OTgsImV4cCI6MjA2MTM0MTk5OH0.t5Zmzx1h3gDLrneWIGY6UdAC20BTip5JHpvrPjeyi8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);